## This file is a general .xdc for the ARTY Rev. A
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project


# Clock signal

set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports sysclk_i]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports sysclk_i]

set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports resetn_i]

#Switches

#set_property -dict { PACKAGE_PIN A8  IOSTANDARD LVCMOS33 } [get_ports { usr_sw[0] }]; #IO_L12N_T1_MRCC_16 Sch=sw[0]
#set_property -dict { PACKAGE_PIN C11 IOSTANDARD LVCMOS33 } [get_ports { usr_sw[1] }]; #IO_L13P_T2_MRCC_16 Sch=sw[1]
#set_property -dict { PACKAGE_PIN C10 IOSTANDARD LVCMOS33 } [get_ports { usr_sw[2] }]; #IO_L13N_T2_MRCC_16 Sch=sw[2]
#set_property -dict { PACKAGE_PIN A10 IOSTANDARD LVCMOS33 } [get_ports { usr_sw[3] }]; #IO_L14P_T2_SRCC_16 Sch=sw[3]


# LEDs

set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports {usr_led[0]}]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {usr_led[1]}]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {usr_led[2]}]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {usr_led[3]}]
#set_property -dict { PACKAGE_PIN E1  IOSTANDARD LVCMOS33 } [get_ports { rgb_led[0] }]; #IO_L18N_T2_35 Sch=led0_b
#set_property -dict { PACKAGE_PIN F6  IOSTANDARD LVCMOS33 } [get_ports { rgb_led[1] }]; #IO_L19N_T3_VREF_35 Sch=led0_g
#set_property -dict { PACKAGE_PIN G6  IOSTANDARD LVCMOS33 } [get_ports { rgb_led[2] }]; #IO_L19P_T3_35 Sch=led0_r
#set_property -dict { PACKAGE_PIN G4  IOSTANDARD LVCMOS33 } [get_ports { rgb_led_b[1] }]; #IO_L20P_T3_35 Sch=led1_b
#set_property -dict { PACKAGE_PIN J4  IOSTANDARD LVCMOS33 } [get_ports { rgb_led_g[1] }]; #IO_L21P_T3_DQS_35 Sch=led1_g
#set_property -dict { PACKAGE_PIN G3  IOSTANDARD LVCMOS33 } [get_ports { rgb_led_r[1] }]; #IO_L20N_T3_35 Sch=led1_r
#set_property -dict { PACKAGE_PIN H4  IOSTANDARD LVCMOS33 } [get_ports { rgb_led_b[2] }]; #IO_L21N_T3_DQS_35 Sch=led2_b
#set_property -dict { PACKAGE_PIN J2  IOSTANDARD LVCMOS33 } [get_ports { rgb_led_g[2] }]; #IO_L22N_T3_35 Sch=led2_g
#set_property -dict { PACKAGE_PIN J3  IOSTANDARD LVCMOS33 } [get_ports { rgb_led_r[2] }]; #IO_L22P_T3_35 Sch=led2_r
#set_property -dict { PACKAGE_PIN K2  IOSTANDARD LVCMOS33 } [get_ports { rgb_led_b[3] }]; #IO_L23P_T3_35 Sch=led3_b
#set_property -dict { PACKAGE_PIN H6  IOSTANDARD LVCMOS33 } [get_ports { rgb_led_g[3] }]; #IO_L24P_T3_35 Sch=led3_g
#set_property -dict { PACKAGE_PIN K1  IOSTANDARD LVCMOS33 } [get_ports { rgb_led_r[3] }]; #IO_L23N_T3_35 Sch=led3_r


#Buttons

set_property -dict {PACKAGE_PIN D9 IOSTANDARD LVCMOS33} [get_ports {usr_btn[0]}]
set_property -dict {PACKAGE_PIN C9 IOSTANDARD LVCMOS33} [get_ports {usr_btn[1]}]
set_property -dict {PACKAGE_PIN B9 IOSTANDARD LVCMOS33} [get_ports {usr_btn[2]}]
set_property -dict {PACKAGE_PIN B8 IOSTANDARD LVCMOS33} [get_ports {usr_btn[3]}]

#UART
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports uart_tx]
set_property -dict {PACKAGE_PIN A9 IOSTANDARD LVCMOS33} [get_ports uart_rx]

##ChipKit Digital I/O Low

#set_property -dict { PACKAGE_PIN V15 IOSTANDARD LVCMOS33 } [get_ports { ck_io[0] }]; #IO_L16P_T2_CSI_B_14 Sch=ck_io[0]
#set_property -dict { PACKAGE_PIN U16 IOSTANDARD LVCMOS33 } [get_ports { ck_io[1] }]; #IO_L18P_T2_A12_D28_14 Sch=ck_io[1]
#set_property -dict { PACKAGE_PIN P14 IOSTANDARD LVCMOS33 } [get_ports { ck_io[2] }]; #IO_L8N_T1_D12_14 Sch=ck_io[2]
#set_property -dict { PACKAGE_PIN T11 IOSTANDARD LVCMOS33 } [get_ports { ck_io[3] }]; #IO_L19P_T3_A10_D26_14 Sch=ck_io[3]
#set_property -dict { PACKAGE_PIN R12 IOSTANDARD LVCMOS33 } [get_ports { ck_io[4] }]; #IO_L5P_T0_D06_14 Sch=ck_io[4]
#set_property -dict { PACKAGE_PIN T14 IOSTANDARD LVCMOS33 } [get_ports { ck_io[5] }]; #IO_L14P_T2_SRCC_14 Sch=ck_io[5]
#set_property -dict { PACKAGE_PIN T15 IOSTANDARD LVCMOS33 } [get_ports { ck_io[6] }]; #IO_L14N_T2_SRCC_14 Sch=ck_io[6]
#set_property -dict { PACKAGE_PIN T16 IOSTANDARD LVCMOS33 } [get_ports { LCD_E }]; #IO_L15N_T2_DQS_DOUT_CSO_B_14 Sch=ck_io[7]
#set_property -dict { PACKAGE_PIN N15 IOSTANDARD LVCMOS33 } [get_ports { LCD_RW }]; #IO_L11P_T1_SRCC_14 Sch=ck_io[8]
#set_property -dict { PACKAGE_PIN M16 IOSTANDARD LVCMOS33 } [get_ports { LCD_RS }]; #IO_L10P_T1_D14_14 Sch=ck_io[9]
#set_property -dict { PACKAGE_PIN V17 IOSTANDARD LVCMOS33 } [get_ports { LCD_D[3] }]; #IO_L18N_T2_A11_D27_14 Sch=ck_io[10]
#set_property -dict { PACKAGE_PIN U18 IOSTANDARD LVCMOS33 } [get_ports { LCD_D[2] }]; #IO_L17N_T2_A13_D29_14 Sch=ck_io[11]
#set_property -dict { PACKAGE_PIN R17 IOSTANDARD LVCMOS33 } [get_ports { LCD_D[1] }]; #IO_L12N_T1_MRCC_14 Sch=ck_io[12]
#set_property -dict { PACKAGE_PIN P17 IOSTANDARD LVCMOS33 } [get_ports { LCD_D[0] }]; #IO_L12P_T1_MRCC_14 Sch=ck_io[13]

##ChipKit Digital I/O High

#set_property -dict { PACKAGE_PIN U11 IOSTANDARD LVCMOS33 } [get_ports { ck_io[26] }]; #IO_L19N_T3_A09_D25_VREF_14 Sch=ck_io[26]
#set_property -dict { PACKAGE_PIN V16 IOSTANDARD LVCMOS33 } [get_ports { ck_io[27] }]; #IO_L16N_T2_A15_D31_14 Sch=ck_io[27]
#set_property -dict { PACKAGE_PIN M13 IOSTANDARD LVCMOS33 } [get_ports { VGA_HSYNC }]; #IO_L6N_T0_D08_VREF_14 Sch=ck_io[28]
#set_property -dict { PACKAGE_PIN R10 IOSTANDARD LVCMOS33 } [get_ports { VGA_VSYNC }]; #IO_25_14 Sch=ck_io[29]
#set_property -dict { PACKAGE_PIN R11 IOSTANDARD LVCMOS33 } [get_ports { VGA_GREEN[0] }]; #IO_0_14 Sch=ck_io[30]
#set_property -dict { PACKAGE_PIN R13 IOSTANDARD LVCMOS33 } [get_ports { VGA_GREEN[1] }]; #IO_L5N_T0_D07_14 Sch=ck_io[31]
#set_property -dict { PACKAGE_PIN R15 IOSTANDARD LVCMOS33 } [get_ports { VGA_GREEN[2] }]; #IO_L13N_T2_MRCC_14 Sch=ck_io[32]
#set_property -dict { PACKAGE_PIN P15 IOSTANDARD LVCMOS33 } [get_ports { VGA_GREEN[3] }]; #IO_L13P_T2_MRCC_14 Sch=ck_io[33]
#set_property -dict { PACKAGE_PIN R16 IOSTANDARD LVCMOS33 } [get_ports { VGA_BLUE[0] }]; #IO_L15P_T2_DQS_RDWR_B_14 Sch=ck_io[34]
#set_property -dict { PACKAGE_PIN N16 IOSTANDARD LVCMOS33 } [get_ports { VGA_BLUE[1] }]; #IO_L11N_T1_SRCC_14 Sch=ck_io[35]
#set_property -dict { PACKAGE_PIN N14 IOSTANDARD LVCMOS33 } [get_ports { VGA_BLUE[2] }]; #IO_L8P_T1_D11_14 Sch=ck_io[36]
#set_property -dict { PACKAGE_PIN U17 IOSTANDARD LVCMOS33 } [get_ports { VGA_BLUE[3] }]; #IO_L17P_T2_A14_D30_14 Sch=ck_io[37]
#set_property -dict { PACKAGE_PIN T18 IOSTANDARD LVCMOS33 } [get_ports { VGA_RED[0] }]; #IO_L7N_T1_D10_14 Sch=ck_io[38]
#set_property -dict { PACKAGE_PIN R18 IOSTANDARD LVCMOS33 } [get_ports { VGA_RED[1] }]; #IO_L7P_T1_D09_14 Sch=ck_io[39]
#set_property -dict { PACKAGE_PIN P18 IOSTANDARD LVCMOS33 } [get_ports { VGA_RED[2] }]; #IO_L9N_T1_DQS_D13_14 Sch=ck_io[40]
#set_property -dict { PACKAGE_PIN N17 IOSTANDARD LVCMOS33 } [get_ports { VGA_RED[3] }]; #IO_L9P_T1_DQS_14 Sch=ck_io[41]

##Misc. ChipKit signals

#set_property -dict { PACKAGE_PIN M17   IOSTANDARD LVCMOS33 } [get_ports { ck_ioa }]; #IO_L10N_T1_D15_14 Sch=ck_ioa
#set_property -dict { PACKAGE_PIN C2    IOSTANDARD LVCMOS33 } [get_ports { ck_rst }]; #IO_L16P_T2_35 Sch=ck_rst

## ChipKit SPI

#set_property -dict { PACKAGE_PIN G1  IOSTANDARD LVCMOS33 } [get_ports { spi_miso }]; #IO_L17N_T2_35 Sch=ck_miso
#set_property -dict { PACKAGE_PIN H1  IOSTANDARD LVCMOS33 } [get_ports { spi_mosi }]; #IO_L17P_T2_35 Sch=ck_mosi
#set_property -dict { PACKAGE_PIN F1  IOSTANDARD LVCMOS33 } [get_ports { spi_sck }]; #IO_L18P_T2_35 Sch=ck_sck
#set_property -dict { PACKAGE_PIN C1  IOSTANDARD LVCMOS33 } [get_ports { spi_ss }]; #IO_L16N_T2_35 Sch=ck_ss


## ChipKit I2C

#set_property -dict { PACKAGE_PIN L18   IOSTANDARD LVCMOS33 } [get_ports { ck_scl }]; #IO_L4P_T0_D04_14 Sch=ck_scl
#set_property -dict { PACKAGE_PIN M18   IOSTANDARD LVCMOS33 } [get_ports { ck_sda }]; #IO_L4N_T0_D05_14 Sch=ck_sda
#set_property -dict { PACKAGE_PIN A14   IOSTANDARD LVCMOS33 } [get_ports { scl_pup }]; #IO_L9N_T1_DQS_AD3N_15 Sch=scl_pup
#set_property -dict { PACKAGE_PIN A13   IOSTANDARD LVCMOS33 } [get_ports { sda_pup }]; #IO_L9P_T1_DQS_AD3P_15 Sch=sda_pup


##SMSC Ethernet PHY

#set_property -dict { PACKAGE_PIN D17   IOSTANDARD LVCMOS33 } [get_ports { eth_col }]; #IO_L16N_T2_A27_15 Sch=eth_col
#set_property -dict { PACKAGE_PIN G14   IOSTANDARD LVCMOS33 } [get_ports { eth_crs }]; #IO_L15N_T2_DQS_ADV_B_15 Sch=eth_crs
#set_property -dict { PACKAGE_PIN F16   IOSTANDARD LVCMOS33 } [get_ports { eth_mdc }]; #IO_L14N_T2_SRCC_15 Sch=eth_mdc
#set_property -dict { PACKAGE_PIN K13   IOSTANDARD LVCMOS33 } [get_ports { eth_mdio }]; #IO_L17P_T2_A26_15 Sch=eth_mdio
#set_property -dict { PACKAGE_PIN G18   IOSTANDARD LVCMOS33 } [get_ports { eth_ref_clk }]; #IO_L22P_T3_A17_15 Sch=eth_ref_clk
#set_property -dict { PACKAGE_PIN C16   IOSTANDARD LVCMOS33 } [get_ports { eth_rstn }]; #IO_L20P_T3_A20_15 Sch=eth_rstn
#set_property -dict { PACKAGE_PIN F15   IOSTANDARD LVCMOS33 } [get_ports { eth_rx_clk }]; #IO_L14P_T2_SRCC_15 Sch=eth_rx_clk
#set_property -dict { PACKAGE_PIN G16   IOSTANDARD LVCMOS33 } [get_ports { eth_rx_dv }]; #IO_L13N_T2_MRCC_15 Sch=eth_rx_dv
#set_property -dict { PACKAGE_PIN D18   IOSTANDARD LVCMOS33 } [get_ports { eth_rxd[0] }]; #IO_L21N_T3_DQS_A18_15 Sch=eth_rxd[0]
#set_property -dict { PACKAGE_PIN E17   IOSTANDARD LVCMOS33 } [get_ports { eth_rxd[1] }]; #IO_L16P_T2_A28_15 Sch=eth_rxd[1]
#set_property -dict { PACKAGE_PIN E18   IOSTANDARD LVCMOS33 } [get_ports { eth_rxd[2] }]; #IO_L21P_T3_DQS_15 Sch=eth_rxd[2]
#set_property -dict { PACKAGE_PIN G17   IOSTANDARD LVCMOS33 } [get_ports { eth_rxd[3] }]; #IO_L18N_T2_A23_15 Sch=eth_rxd[3]
#set_property -dict { PACKAGE_PIN C17   IOSTANDARD LVCMOS33 } [get_ports { eth_rxerr }]; #IO_L20N_T3_A19_15 Sch=eth_rxerr
#set_property -dict { PACKAGE_PIN H16   IOSTANDARD LVCMOS33 } [get_ports { eth_tx_clk }]; #IO_L13P_T2_MRCC_15 Sch=eth_tx_clk
#set_property -dict { PACKAGE_PIN H15   IOSTANDARD LVCMOS33 } [get_ports { eth_tx_en }]; #IO_L19N_T3_A21_VREF_15 Sch=eth_tx_en
#set_property -dict { PACKAGE_PIN H14   IOSTANDARD LVCMOS33 } [get_ports { eth_txd[0] }]; #IO_L15P_T2_DQS_15 Sch=eth_txd[0]
#set_property -dict { PACKAGE_PIN J14   IOSTANDARD LVCMOS33 } [get_ports { eth_txd[1] }]; #IO_L19P_T3_A22_15 Sch=eth_txd[1]
#set_property -dict { PACKAGE_PIN J13   IOSTANDARD LVCMOS33 } [get_ports { eth_txd[2] }]; #IO_L17N_T2_A25_15 Sch=eth_txd[2]
#set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { eth_txd[3] }]; #IO_L18P_T2_A24_15 Sch=eth_txd[3]


##Quad SPI Flash

#set_property -dict { PACKAGE_PIN L13   IOSTANDARD LVCMOS33 } [get_ports { qspi_cs }]; #IO_L6P_T0_FCS_B_14 Sch=qspi_cs
#set_property -dict { PACKAGE_PIN K17   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[0] }]; #IO_L1P_T0_D00_MOSI_14 Sch=qspi_dq[0]
#set_property -dict { PACKAGE_PIN K18   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[1] }]; #IO_L1N_T0_D01_DIN_14 Sch=qspi_dq[1]
#set_property -dict { PACKAGE_PIN L14   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[2] }]; #IO_L2P_T0_D02_14 Sch=qspi_dq[2]
#set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports { qspi_dq[3] }]; #IO_L2N_T0_D03_14 Sch=qspi_dq[3]


##Power Analysis

#set_property -dict { PACKAGE_PIN A16   IOSTANDARD LVCMOS33 } [get_ports { sns0v_n[95] }]; #IO_L8N_T1_AD10N_15 Sch=sns0v_n[95]
#set_property -dict { PACKAGE_PIN A15   IOSTANDARD LVCMOS33 } [get_ports { sns0v_p[95] }]; #IO_L8P_T1_AD10P_15 Sch=sns0v_p[95]
#set_property -dict { PACKAGE_PIN F14   IOSTANDARD LVCMOS33 } [get_ports { sns5v_n[0] }]; #IO_L5N_T0_AD9N_15 Sch=sns5v_n[0]
#set_property -dict { PACKAGE_PIN F13   IOSTANDARD LVCMOS33 } [get_ports { sns5v_p[0] }]; #IO_L5P_T0_AD9P_15 Sch=sns5v_p[0]
#set_property -dict { PACKAGE_PIN C12   IOSTANDARD LVCMOS33 } [get_ports { vsns5v[0] }]; #IO_L3P_T0_DQS_AD1P_15 Sch=vsns5v[0]
#set_property -dict { PACKAGE_PIN B16   IOSTANDARD LVCMOS33 } [get_ports { vsnsvu }]; #IO_L7P_T1_AD2P_15 Sch=vsnsvu

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

connect_debug_port u_ila_0/probe1 [get_nets [list {Aquila_SoC/D_Cache/hit[0]} {Aquila_SoC/D_Cache/hit[1]} {Aquila_SoC/D_Cache/hit[2]} {Aquila_SoC/D_Cache/hit[3]} {Aquila_SoC/D_Cache/hit[4]} {Aquila_SoC/D_Cache/hit[5]} {Aquila_SoC/D_Cache/hit[6]} {Aquila_SoC/D_Cache/hit[7]} {Aquila_SoC/D_Cache/hit[8]} {Aquila_SoC/D_Cache/hit[9]} {Aquila_SoC/D_Cache/hit[10]} {Aquila_SoC/D_Cache/hit[11]} {Aquila_SoC/D_Cache/hit[12]} {Aquila_SoC/D_Cache/hit[13]} {Aquila_SoC/D_Cache/hit[14]} {Aquila_SoC/D_Cache/hit[15]} {Aquila_SoC/D_Cache/hit[16]} {Aquila_SoC/D_Cache/hit[17]} {Aquila_SoC/D_Cache/hit[18]} {Aquila_SoC/D_Cache/hit[19]} {Aquila_SoC/D_Cache/hit[20]} {Aquila_SoC/D_Cache/hit[21]} {Aquila_SoC/D_Cache/hit[22]} {Aquila_SoC/D_Cache/hit[23]} {Aquila_SoC/D_Cache/hit[24]} {Aquila_SoC/D_Cache/hit[25]} {Aquila_SoC/D_Cache/hit[26]} {Aquila_SoC/D_Cache/hit[27]} {Aquila_SoC/D_Cache/hit[28]} {Aquila_SoC/D_Cache/hit[29]} {Aquila_SoC/D_Cache/hit[30]} {Aquila_SoC/D_Cache/hit[31]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {Aquila_SoC/D_Cache/total[0]} {Aquila_SoC/D_Cache/total[1]} {Aquila_SoC/D_Cache/total[2]} {Aquila_SoC/D_Cache/total[3]} {Aquila_SoC/D_Cache/total[4]} {Aquila_SoC/D_Cache/total[5]} {Aquila_SoC/D_Cache/total[6]} {Aquila_SoC/D_Cache/total[7]} {Aquila_SoC/D_Cache/total[8]} {Aquila_SoC/D_Cache/total[9]} {Aquila_SoC/D_Cache/total[10]} {Aquila_SoC/D_Cache/total[11]} {Aquila_SoC/D_Cache/total[12]} {Aquila_SoC/D_Cache/total[13]} {Aquila_SoC/D_Cache/total[14]} {Aquila_SoC/D_Cache/total[15]} {Aquila_SoC/D_Cache/total[16]} {Aquila_SoC/D_Cache/total[17]} {Aquila_SoC/D_Cache/total[18]} {Aquila_SoC/D_Cache/total[19]} {Aquila_SoC/D_Cache/total[20]} {Aquila_SoC/D_Cache/total[21]} {Aquila_SoC/D_Cache/total[22]} {Aquila_SoC/D_Cache/total[23]} {Aquila_SoC/D_Cache/total[24]} {Aquila_SoC/D_Cache/total[25]} {Aquila_SoC/D_Cache/total[26]} {Aquila_SoC/D_Cache/total[27]} {Aquila_SoC/D_Cache/total[28]} {Aquila_SoC/D_Cache/total[29]} {Aquila_SoC/D_Cache/total[30]} {Aquila_SoC/D_Cache/total[31]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {Aquila_SoC/D_Cache/read[0]} {Aquila_SoC/D_Cache/read[1]} {Aquila_SoC/D_Cache/read[2]} {Aquila_SoC/D_Cache/read[3]} {Aquila_SoC/D_Cache/read[4]} {Aquila_SoC/D_Cache/read[5]} {Aquila_SoC/D_Cache/read[6]} {Aquila_SoC/D_Cache/read[7]} {Aquila_SoC/D_Cache/read[8]} {Aquila_SoC/D_Cache/read[9]} {Aquila_SoC/D_Cache/read[10]} {Aquila_SoC/D_Cache/read[11]} {Aquila_SoC/D_Cache/read[12]} {Aquila_SoC/D_Cache/read[13]} {Aquila_SoC/D_Cache/read[14]} {Aquila_SoC/D_Cache/read[15]} {Aquila_SoC/D_Cache/read[16]} {Aquila_SoC/D_Cache/read[17]} {Aquila_SoC/D_Cache/read[18]} {Aquila_SoC/D_Cache/read[19]} {Aquila_SoC/D_Cache/read[20]} {Aquila_SoC/D_Cache/read[21]} {Aquila_SoC/D_Cache/read[22]} {Aquila_SoC/D_Cache/read[23]} {Aquila_SoC/D_Cache/read[24]} {Aquila_SoC/D_Cache/read[25]} {Aquila_SoC/D_Cache/read[26]} {Aquila_SoC/D_Cache/read[27]} {Aquila_SoC/D_Cache/read[28]} {Aquila_SoC/D_Cache/read[29]} {Aquila_SoC/D_Cache/read[30]} {Aquila_SoC/D_Cache/read[31]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {Aquila_SoC/D_Cache/miss[0]} {Aquila_SoC/D_Cache/miss[1]} {Aquila_SoC/D_Cache/miss[2]} {Aquila_SoC/D_Cache/miss[3]} {Aquila_SoC/D_Cache/miss[4]} {Aquila_SoC/D_Cache/miss[5]} {Aquila_SoC/D_Cache/miss[6]} {Aquila_SoC/D_Cache/miss[7]} {Aquila_SoC/D_Cache/miss[8]} {Aquila_SoC/D_Cache/miss[9]} {Aquila_SoC/D_Cache/miss[10]} {Aquila_SoC/D_Cache/miss[11]} {Aquila_SoC/D_Cache/miss[12]} {Aquila_SoC/D_Cache/miss[13]} {Aquila_SoC/D_Cache/miss[14]} {Aquila_SoC/D_Cache/miss[15]} {Aquila_SoC/D_Cache/miss[16]} {Aquila_SoC/D_Cache/miss[17]} {Aquila_SoC/D_Cache/miss[18]} {Aquila_SoC/D_Cache/miss[19]} {Aquila_SoC/D_Cache/miss[20]} {Aquila_SoC/D_Cache/miss[21]} {Aquila_SoC/D_Cache/miss[22]} {Aquila_SoC/D_Cache/miss[23]} {Aquila_SoC/D_Cache/miss[24]} {Aquila_SoC/D_Cache/miss[25]} {Aquila_SoC/D_Cache/miss[26]} {Aquila_SoC/D_Cache/miss[27]} {Aquila_SoC/D_Cache/miss[28]} {Aquila_SoC/D_Cache/miss[29]} {Aquila_SoC/D_Cache/miss[30]} {Aquila_SoC/D_Cache/miss[31]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {Aquila_SoC/D_Cache/write[0]} {Aquila_SoC/D_Cache/write[1]} {Aquila_SoC/D_Cache/write[2]} {Aquila_SoC/D_Cache/write[3]} {Aquila_SoC/D_Cache/write[4]} {Aquila_SoC/D_Cache/write[5]} {Aquila_SoC/D_Cache/write[6]} {Aquila_SoC/D_Cache/write[7]} {Aquila_SoC/D_Cache/write[8]} {Aquila_SoC/D_Cache/write[9]} {Aquila_SoC/D_Cache/write[10]} {Aquila_SoC/D_Cache/write[11]} {Aquila_SoC/D_Cache/write[12]} {Aquila_SoC/D_Cache/write[13]} {Aquila_SoC/D_Cache/write[14]} {Aquila_SoC/D_Cache/write[15]} {Aquila_SoC/D_Cache/write[16]} {Aquila_SoC/D_Cache/write[17]} {Aquila_SoC/D_Cache/write[18]} {Aquila_SoC/D_Cache/write[19]} {Aquila_SoC/D_Cache/write[20]} {Aquila_SoC/D_Cache/write[21]} {Aquila_SoC/D_Cache/write[22]} {Aquila_SoC/D_Cache/write[23]} {Aquila_SoC/D_Cache/write[24]} {Aquila_SoC/D_Cache/write[25]} {Aquila_SoC/D_Cache/write[26]} {Aquila_SoC/D_Cache/write[27]} {Aquila_SoC/D_Cache/write[28]} {Aquila_SoC/D_Cache/write[29]} {Aquila_SoC/D_Cache/write[30]} {Aquila_SoC/D_Cache/write[31]}]]




connect_debug_port u_ila_0/probe7 [get_nets [list Aquila_SoC/D_Cache/p_strobe_i0]]




connect_debug_port u_ila_0/probe0 [get_nets [list {Aquila_SoC/D_Cache/hit_latency[0]} {Aquila_SoC/D_Cache/hit_latency[1]} {Aquila_SoC/D_Cache/hit_latency[2]} {Aquila_SoC/D_Cache/hit_latency[3]} {Aquila_SoC/D_Cache/hit_latency[4]} {Aquila_SoC/D_Cache/hit_latency[5]} {Aquila_SoC/D_Cache/hit_latency[6]} {Aquila_SoC/D_Cache/hit_latency[7]} {Aquila_SoC/D_Cache/hit_latency[8]} {Aquila_SoC/D_Cache/hit_latency[9]} {Aquila_SoC/D_Cache/hit_latency[10]} {Aquila_SoC/D_Cache/hit_latency[11]} {Aquila_SoC/D_Cache/hit_latency[12]} {Aquila_SoC/D_Cache/hit_latency[13]} {Aquila_SoC/D_Cache/hit_latency[14]} {Aquila_SoC/D_Cache/hit_latency[15]} {Aquila_SoC/D_Cache/hit_latency[16]} {Aquila_SoC/D_Cache/hit_latency[17]} {Aquila_SoC/D_Cache/hit_latency[18]} {Aquila_SoC/D_Cache/hit_latency[19]} {Aquila_SoC/D_Cache/hit_latency[20]} {Aquila_SoC/D_Cache/hit_latency[21]} {Aquila_SoC/D_Cache/hit_latency[22]} {Aquila_SoC/D_Cache/hit_latency[23]} {Aquila_SoC/D_Cache/hit_latency[24]} {Aquila_SoC/D_Cache/hit_latency[25]} {Aquila_SoC/D_Cache/hit_latency[26]} {Aquila_SoC/D_Cache/hit_latency[27]} {Aquila_SoC/D_Cache/hit_latency[28]} {Aquila_SoC/D_Cache/hit_latency[29]} {Aquila_SoC/D_Cache/hit_latency[30]} {Aquila_SoC/D_Cache/hit_latency[31]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {Aquila_SoC/D_Cache/read_latency[0]} {Aquila_SoC/D_Cache/read_latency[1]} {Aquila_SoC/D_Cache/read_latency[2]} {Aquila_SoC/D_Cache/read_latency[3]} {Aquila_SoC/D_Cache/read_latency[4]} {Aquila_SoC/D_Cache/read_latency[5]} {Aquila_SoC/D_Cache/read_latency[6]} {Aquila_SoC/D_Cache/read_latency[7]} {Aquila_SoC/D_Cache/read_latency[8]} {Aquila_SoC/D_Cache/read_latency[9]} {Aquila_SoC/D_Cache/read_latency[10]} {Aquila_SoC/D_Cache/read_latency[11]} {Aquila_SoC/D_Cache/read_latency[12]} {Aquila_SoC/D_Cache/read_latency[13]} {Aquila_SoC/D_Cache/read_latency[14]} {Aquila_SoC/D_Cache/read_latency[15]} {Aquila_SoC/D_Cache/read_latency[16]} {Aquila_SoC/D_Cache/read_latency[17]} {Aquila_SoC/D_Cache/read_latency[18]} {Aquila_SoC/D_Cache/read_latency[19]} {Aquila_SoC/D_Cache/read_latency[20]} {Aquila_SoC/D_Cache/read_latency[21]} {Aquila_SoC/D_Cache/read_latency[22]} {Aquila_SoC/D_Cache/read_latency[23]} {Aquila_SoC/D_Cache/read_latency[24]} {Aquila_SoC/D_Cache/read_latency[25]} {Aquila_SoC/D_Cache/read_latency[26]} {Aquila_SoC/D_Cache/read_latency[27]} {Aquila_SoC/D_Cache/read_latency[28]} {Aquila_SoC/D_Cache/read_latency[29]} {Aquila_SoC/D_Cache/read_latency[30]} {Aquila_SoC/D_Cache/read_latency[31]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {Aquila_SoC/D_Cache/miss_latency[0]} {Aquila_SoC/D_Cache/miss_latency[1]} {Aquila_SoC/D_Cache/miss_latency[2]} {Aquila_SoC/D_Cache/miss_latency[3]} {Aquila_SoC/D_Cache/miss_latency[4]} {Aquila_SoC/D_Cache/miss_latency[5]} {Aquila_SoC/D_Cache/miss_latency[6]} {Aquila_SoC/D_Cache/miss_latency[7]} {Aquila_SoC/D_Cache/miss_latency[8]} {Aquila_SoC/D_Cache/miss_latency[9]} {Aquila_SoC/D_Cache/miss_latency[10]} {Aquila_SoC/D_Cache/miss_latency[11]} {Aquila_SoC/D_Cache/miss_latency[12]} {Aquila_SoC/D_Cache/miss_latency[13]} {Aquila_SoC/D_Cache/miss_latency[14]} {Aquila_SoC/D_Cache/miss_latency[15]} {Aquila_SoC/D_Cache/miss_latency[16]} {Aquila_SoC/D_Cache/miss_latency[17]} {Aquila_SoC/D_Cache/miss_latency[18]} {Aquila_SoC/D_Cache/miss_latency[19]} {Aquila_SoC/D_Cache/miss_latency[20]} {Aquila_SoC/D_Cache/miss_latency[21]} {Aquila_SoC/D_Cache/miss_latency[22]} {Aquila_SoC/D_Cache/miss_latency[23]} {Aquila_SoC/D_Cache/miss_latency[24]} {Aquila_SoC/D_Cache/miss_latency[25]} {Aquila_SoC/D_Cache/miss_latency[26]} {Aquila_SoC/D_Cache/miss_latency[27]} {Aquila_SoC/D_Cache/miss_latency[28]} {Aquila_SoC/D_Cache/miss_latency[29]} {Aquila_SoC/D_Cache/miss_latency[30]} {Aquila_SoC/D_Cache/miss_latency[31]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {Aquila_SoC/D_Cache/write_latency[0]} {Aquila_SoC/D_Cache/write_latency[1]} {Aquila_SoC/D_Cache/write_latency[2]} {Aquila_SoC/D_Cache/write_latency[3]} {Aquila_SoC/D_Cache/write_latency[4]} {Aquila_SoC/D_Cache/write_latency[5]} {Aquila_SoC/D_Cache/write_latency[6]} {Aquila_SoC/D_Cache/write_latency[7]} {Aquila_SoC/D_Cache/write_latency[8]} {Aquila_SoC/D_Cache/write_latency[9]} {Aquila_SoC/D_Cache/write_latency[10]} {Aquila_SoC/D_Cache/write_latency[11]} {Aquila_SoC/D_Cache/write_latency[12]} {Aquila_SoC/D_Cache/write_latency[13]} {Aquila_SoC/D_Cache/write_latency[14]} {Aquila_SoC/D_Cache/write_latency[15]} {Aquila_SoC/D_Cache/write_latency[16]} {Aquila_SoC/D_Cache/write_latency[17]} {Aquila_SoC/D_Cache/write_latency[18]} {Aquila_SoC/D_Cache/write_latency[19]} {Aquila_SoC/D_Cache/write_latency[20]} {Aquila_SoC/D_Cache/write_latency[21]} {Aquila_SoC/D_Cache/write_latency[22]} {Aquila_SoC/D_Cache/write_latency[23]} {Aquila_SoC/D_Cache/write_latency[24]} {Aquila_SoC/D_Cache/write_latency[25]} {Aquila_SoC/D_Cache/write_latency[26]} {Aquila_SoC/D_Cache/write_latency[27]} {Aquila_SoC/D_Cache/write_latency[28]} {Aquila_SoC/D_Cache/write_latency[29]} {Aquila_SoC/D_Cache/write_latency[30]} {Aquila_SoC/D_Cache/write_latency[31]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list Aquila_SoC/D_Cache/cache_hit]]

connect_debug_port u_ila_0/probe1 [get_nets [list {Aquila_SoC/D_Cache/miss_read[0]} {Aquila_SoC/D_Cache/miss_read[1]} {Aquila_SoC/D_Cache/miss_read[2]} {Aquila_SoC/D_Cache/miss_read[3]} {Aquila_SoC/D_Cache/miss_read[4]} {Aquila_SoC/D_Cache/miss_read[5]} {Aquila_SoC/D_Cache/miss_read[6]} {Aquila_SoC/D_Cache/miss_read[7]} {Aquila_SoC/D_Cache/miss_read[8]} {Aquila_SoC/D_Cache/miss_read[9]} {Aquila_SoC/D_Cache/miss_read[10]} {Aquila_SoC/D_Cache/miss_read[11]} {Aquila_SoC/D_Cache/miss_read[12]} {Aquila_SoC/D_Cache/miss_read[13]} {Aquila_SoC/D_Cache/miss_read[14]} {Aquila_SoC/D_Cache/miss_read[15]} {Aquila_SoC/D_Cache/miss_read[16]} {Aquila_SoC/D_Cache/miss_read[17]} {Aquila_SoC/D_Cache/miss_read[18]} {Aquila_SoC/D_Cache/miss_read[19]} {Aquila_SoC/D_Cache/miss_read[20]} {Aquila_SoC/D_Cache/miss_read[21]} {Aquila_SoC/D_Cache/miss_read[22]} {Aquila_SoC/D_Cache/miss_read[23]} {Aquila_SoC/D_Cache/miss_read[24]} {Aquila_SoC/D_Cache/miss_read[25]} {Aquila_SoC/D_Cache/miss_read[26]} {Aquila_SoC/D_Cache/miss_read[27]} {Aquila_SoC/D_Cache/miss_read[28]} {Aquila_SoC/D_Cache/miss_read[29]} {Aquila_SoC/D_Cache/miss_read[30]} {Aquila_SoC/D_Cache/miss_read[31]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {Aquila_SoC/D_Cache/miss_write[0]} {Aquila_SoC/D_Cache/miss_write[1]} {Aquila_SoC/D_Cache/miss_write[2]} {Aquila_SoC/D_Cache/miss_write[3]} {Aquila_SoC/D_Cache/miss_write[4]} {Aquila_SoC/D_Cache/miss_write[5]} {Aquila_SoC/D_Cache/miss_write[6]} {Aquila_SoC/D_Cache/miss_write[7]} {Aquila_SoC/D_Cache/miss_write[8]} {Aquila_SoC/D_Cache/miss_write[9]} {Aquila_SoC/D_Cache/miss_write[10]} {Aquila_SoC/D_Cache/miss_write[11]} {Aquila_SoC/D_Cache/miss_write[12]} {Aquila_SoC/D_Cache/miss_write[13]} {Aquila_SoC/D_Cache/miss_write[14]} {Aquila_SoC/D_Cache/miss_write[15]} {Aquila_SoC/D_Cache/miss_write[16]} {Aquila_SoC/D_Cache/miss_write[17]} {Aquila_SoC/D_Cache/miss_write[18]} {Aquila_SoC/D_Cache/miss_write[19]} {Aquila_SoC/D_Cache/miss_write[20]} {Aquila_SoC/D_Cache/miss_write[21]} {Aquila_SoC/D_Cache/miss_write[22]} {Aquila_SoC/D_Cache/miss_write[23]} {Aquila_SoC/D_Cache/miss_write[24]} {Aquila_SoC/D_Cache/miss_write[25]} {Aquila_SoC/D_Cache/miss_write[26]} {Aquila_SoC/D_Cache/miss_write[27]} {Aquila_SoC/D_Cache/miss_write[28]} {Aquila_SoC/D_Cache/miss_write[29]} {Aquila_SoC/D_Cache/miss_write[30]} {Aquila_SoC/D_Cache/miss_write[31]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {Aquila_SoC/D_Cache/read[0]} {Aquila_SoC/D_Cache/read[1]} {Aquila_SoC/D_Cache/read[2]} {Aquila_SoC/D_Cache/read[3]} {Aquila_SoC/D_Cache/read[4]} {Aquila_SoC/D_Cache/read[5]} {Aquila_SoC/D_Cache/read[6]} {Aquila_SoC/D_Cache/read[7]} {Aquila_SoC/D_Cache/read[8]} {Aquila_SoC/D_Cache/read[9]} {Aquila_SoC/D_Cache/read[10]} {Aquila_SoC/D_Cache/read[11]} {Aquila_SoC/D_Cache/read[12]} {Aquila_SoC/D_Cache/read[13]} {Aquila_SoC/D_Cache/read[14]} {Aquila_SoC/D_Cache/read[15]} {Aquila_SoC/D_Cache/read[16]} {Aquila_SoC/D_Cache/read[17]} {Aquila_SoC/D_Cache/read[18]} {Aquila_SoC/D_Cache/read[19]} {Aquila_SoC/D_Cache/read[20]} {Aquila_SoC/D_Cache/read[21]} {Aquila_SoC/D_Cache/read[22]} {Aquila_SoC/D_Cache/read[23]} {Aquila_SoC/D_Cache/read[24]} {Aquila_SoC/D_Cache/read[25]} {Aquila_SoC/D_Cache/read[26]} {Aquila_SoC/D_Cache/read[27]} {Aquila_SoC/D_Cache/read[28]} {Aquila_SoC/D_Cache/read[29]} {Aquila_SoC/D_Cache/read[30]} {Aquila_SoC/D_Cache/read[31]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {Aquila_SoC/D_Cache/write[0]} {Aquila_SoC/D_Cache/write[1]} {Aquila_SoC/D_Cache/write[2]} {Aquila_SoC/D_Cache/write[3]} {Aquila_SoC/D_Cache/write[4]} {Aquila_SoC/D_Cache/write[5]} {Aquila_SoC/D_Cache/write[6]} {Aquila_SoC/D_Cache/write[7]} {Aquila_SoC/D_Cache/write[8]} {Aquila_SoC/D_Cache/write[9]} {Aquila_SoC/D_Cache/write[10]} {Aquila_SoC/D_Cache/write[11]} {Aquila_SoC/D_Cache/write[12]} {Aquila_SoC/D_Cache/write[13]} {Aquila_SoC/D_Cache/write[14]} {Aquila_SoC/D_Cache/write[15]} {Aquila_SoC/D_Cache/write[16]} {Aquila_SoC/D_Cache/write[17]} {Aquila_SoC/D_Cache/write[18]} {Aquila_SoC/D_Cache/write[19]} {Aquila_SoC/D_Cache/write[20]} {Aquila_SoC/D_Cache/write[21]} {Aquila_SoC/D_Cache/write[22]} {Aquila_SoC/D_Cache/write[23]} {Aquila_SoC/D_Cache/write[24]} {Aquila_SoC/D_Cache/write[25]} {Aquila_SoC/D_Cache/write[26]} {Aquila_SoC/D_Cache/write[27]} {Aquila_SoC/D_Cache/write[28]} {Aquila_SoC/D_Cache/write[29]} {Aquila_SoC/D_Cache/write[30]} {Aquila_SoC/D_Cache/write[31]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {Aquila_SoC/D_Cache/total[0]} {Aquila_SoC/D_Cache/total[1]} {Aquila_SoC/D_Cache/total[2]} {Aquila_SoC/D_Cache/total[3]} {Aquila_SoC/D_Cache/total[4]} {Aquila_SoC/D_Cache/total[5]} {Aquila_SoC/D_Cache/total[6]} {Aquila_SoC/D_Cache/total[7]} {Aquila_SoC/D_Cache/total[8]} {Aquila_SoC/D_Cache/total[9]} {Aquila_SoC/D_Cache/total[10]} {Aquila_SoC/D_Cache/total[11]} {Aquila_SoC/D_Cache/total[12]} {Aquila_SoC/D_Cache/total[13]} {Aquila_SoC/D_Cache/total[14]} {Aquila_SoC/D_Cache/total[15]} {Aquila_SoC/D_Cache/total[16]} {Aquila_SoC/D_Cache/total[17]} {Aquila_SoC/D_Cache/total[18]} {Aquila_SoC/D_Cache/total[19]} {Aquila_SoC/D_Cache/total[20]} {Aquila_SoC/D_Cache/total[21]} {Aquila_SoC/D_Cache/total[22]} {Aquila_SoC/D_Cache/total[23]} {Aquila_SoC/D_Cache/total[24]} {Aquila_SoC/D_Cache/total[25]} {Aquila_SoC/D_Cache/total[26]} {Aquila_SoC/D_Cache/total[27]} {Aquila_SoC/D_Cache/total[28]} {Aquila_SoC/D_Cache/total[29]} {Aquila_SoC/D_Cache/total[30]} {Aquila_SoC/D_Cache/total[31]}]]

connect_debug_port u_ila_0/probe1 [get_nets [list {Aquila_SoC/D_Cache/miss_latency[0]} {Aquila_SoC/D_Cache/miss_latency[1]} {Aquila_SoC/D_Cache/miss_latency[2]} {Aquila_SoC/D_Cache/miss_latency[3]} {Aquila_SoC/D_Cache/miss_latency[4]} {Aquila_SoC/D_Cache/miss_latency[5]} {Aquila_SoC/D_Cache/miss_latency[6]} {Aquila_SoC/D_Cache/miss_latency[7]} {Aquila_SoC/D_Cache/miss_latency[8]} {Aquila_SoC/D_Cache/miss_latency[9]} {Aquila_SoC/D_Cache/miss_latency[10]} {Aquila_SoC/D_Cache/miss_latency[11]} {Aquila_SoC/D_Cache/miss_latency[12]} {Aquila_SoC/D_Cache/miss_latency[13]} {Aquila_SoC/D_Cache/miss_latency[14]} {Aquila_SoC/D_Cache/miss_latency[15]} {Aquila_SoC/D_Cache/miss_latency[16]} {Aquila_SoC/D_Cache/miss_latency[17]} {Aquila_SoC/D_Cache/miss_latency[18]} {Aquila_SoC/D_Cache/miss_latency[19]} {Aquila_SoC/D_Cache/miss_latency[20]} {Aquila_SoC/D_Cache/miss_latency[21]} {Aquila_SoC/D_Cache/miss_latency[22]} {Aquila_SoC/D_Cache/miss_latency[23]} {Aquila_SoC/D_Cache/miss_latency[24]} {Aquila_SoC/D_Cache/miss_latency[25]} {Aquila_SoC/D_Cache/miss_latency[26]} {Aquila_SoC/D_Cache/miss_latency[27]} {Aquila_SoC/D_Cache/miss_latency[28]} {Aquila_SoC/D_Cache/miss_latency[29]} {Aquila_SoC/D_Cache/miss_latency[30]} {Aquila_SoC/D_Cache/miss_latency[31]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {Aquila_SoC/D_Cache/hit_latency[0]} {Aquila_SoC/D_Cache/hit_latency[1]} {Aquila_SoC/D_Cache/hit_latency[2]} {Aquila_SoC/D_Cache/hit_latency[3]} {Aquila_SoC/D_Cache/hit_latency[4]} {Aquila_SoC/D_Cache/hit_latency[5]} {Aquila_SoC/D_Cache/hit_latency[6]} {Aquila_SoC/D_Cache/hit_latency[7]} {Aquila_SoC/D_Cache/hit_latency[8]} {Aquila_SoC/D_Cache/hit_latency[9]} {Aquila_SoC/D_Cache/hit_latency[10]} {Aquila_SoC/D_Cache/hit_latency[11]} {Aquila_SoC/D_Cache/hit_latency[12]} {Aquila_SoC/D_Cache/hit_latency[13]} {Aquila_SoC/D_Cache/hit_latency[14]} {Aquila_SoC/D_Cache/hit_latency[15]} {Aquila_SoC/D_Cache/hit_latency[16]} {Aquila_SoC/D_Cache/hit_latency[17]} {Aquila_SoC/D_Cache/hit_latency[18]} {Aquila_SoC/D_Cache/hit_latency[19]} {Aquila_SoC/D_Cache/hit_latency[20]} {Aquila_SoC/D_Cache/hit_latency[21]} {Aquila_SoC/D_Cache/hit_latency[22]} {Aquila_SoC/D_Cache/hit_latency[23]} {Aquila_SoC/D_Cache/hit_latency[24]} {Aquila_SoC/D_Cache/hit_latency[25]} {Aquila_SoC/D_Cache/hit_latency[26]} {Aquila_SoC/D_Cache/hit_latency[27]} {Aquila_SoC/D_Cache/hit_latency[28]} {Aquila_SoC/D_Cache/hit_latency[29]} {Aquila_SoC/D_Cache/hit_latency[30]} {Aquila_SoC/D_Cache/hit_latency[31]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {Aquila_SoC/D_Cache/read_latency[0]} {Aquila_SoC/D_Cache/read_latency[1]} {Aquila_SoC/D_Cache/read_latency[2]} {Aquila_SoC/D_Cache/read_latency[3]} {Aquila_SoC/D_Cache/read_latency[4]} {Aquila_SoC/D_Cache/read_latency[5]} {Aquila_SoC/D_Cache/read_latency[6]} {Aquila_SoC/D_Cache/read_latency[7]} {Aquila_SoC/D_Cache/read_latency[8]} {Aquila_SoC/D_Cache/read_latency[9]} {Aquila_SoC/D_Cache/read_latency[10]} {Aquila_SoC/D_Cache/read_latency[11]} {Aquila_SoC/D_Cache/read_latency[12]} {Aquila_SoC/D_Cache/read_latency[13]} {Aquila_SoC/D_Cache/read_latency[14]} {Aquila_SoC/D_Cache/read_latency[15]} {Aquila_SoC/D_Cache/read_latency[16]} {Aquila_SoC/D_Cache/read_latency[17]} {Aquila_SoC/D_Cache/read_latency[18]} {Aquila_SoC/D_Cache/read_latency[19]} {Aquila_SoC/D_Cache/read_latency[20]} {Aquila_SoC/D_Cache/read_latency[21]} {Aquila_SoC/D_Cache/read_latency[22]} {Aquila_SoC/D_Cache/read_latency[23]} {Aquila_SoC/D_Cache/read_latency[24]} {Aquila_SoC/D_Cache/read_latency[25]} {Aquila_SoC/D_Cache/read_latency[26]} {Aquila_SoC/D_Cache/read_latency[27]} {Aquila_SoC/D_Cache/read_latency[28]} {Aquila_SoC/D_Cache/read_latency[29]} {Aquila_SoC/D_Cache/read_latency[30]} {Aquila_SoC/D_Cache/read_latency[31]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {Aquila_SoC/D_Cache/write_latency[0]} {Aquila_SoC/D_Cache/write_latency[1]} {Aquila_SoC/D_Cache/write_latency[2]} {Aquila_SoC/D_Cache/write_latency[3]} {Aquila_SoC/D_Cache/write_latency[4]} {Aquila_SoC/D_Cache/write_latency[5]} {Aquila_SoC/D_Cache/write_latency[6]} {Aquila_SoC/D_Cache/write_latency[7]} {Aquila_SoC/D_Cache/write_latency[8]} {Aquila_SoC/D_Cache/write_latency[9]} {Aquila_SoC/D_Cache/write_latency[10]} {Aquila_SoC/D_Cache/write_latency[11]} {Aquila_SoC/D_Cache/write_latency[12]} {Aquila_SoC/D_Cache/write_latency[13]} {Aquila_SoC/D_Cache/write_latency[14]} {Aquila_SoC/D_Cache/write_latency[15]} {Aquila_SoC/D_Cache/write_latency[16]} {Aquila_SoC/D_Cache/write_latency[17]} {Aquila_SoC/D_Cache/write_latency[18]} {Aquila_SoC/D_Cache/write_latency[19]} {Aquila_SoC/D_Cache/write_latency[20]} {Aquila_SoC/D_Cache/write_latency[21]} {Aquila_SoC/D_Cache/write_latency[22]} {Aquila_SoC/D_Cache/write_latency[23]} {Aquila_SoC/D_Cache/write_latency[24]} {Aquila_SoC/D_Cache/write_latency[25]} {Aquila_SoC/D_Cache/write_latency[26]} {Aquila_SoC/D_Cache/write_latency[27]} {Aquila_SoC/D_Cache/write_latency[28]} {Aquila_SoC/D_Cache/write_latency[29]} {Aquila_SoC/D_Cache/write_latency[30]} {Aquila_SoC/D_Cache/write_latency[31]}]]


connect_debug_port u_ila_0/probe1 [get_nets [list {Aquila_SoC/D_Cache/miss_read[0]} {Aquila_SoC/D_Cache/miss_read[1]} {Aquila_SoC/D_Cache/miss_read[2]} {Aquila_SoC/D_Cache/miss_read[3]} {Aquila_SoC/D_Cache/miss_read[4]} {Aquila_SoC/D_Cache/miss_read[5]} {Aquila_SoC/D_Cache/miss_read[6]} {Aquila_SoC/D_Cache/miss_read[7]} {Aquila_SoC/D_Cache/miss_read[8]} {Aquila_SoC/D_Cache/miss_read[9]} {Aquila_SoC/D_Cache/miss_read[10]} {Aquila_SoC/D_Cache/miss_read[11]} {Aquila_SoC/D_Cache/miss_read[12]} {Aquila_SoC/D_Cache/miss_read[13]} {Aquila_SoC/D_Cache/miss_read[14]} {Aquila_SoC/D_Cache/miss_read[15]} {Aquila_SoC/D_Cache/miss_read[16]} {Aquila_SoC/D_Cache/miss_read[17]} {Aquila_SoC/D_Cache/miss_read[18]} {Aquila_SoC/D_Cache/miss_read[19]} {Aquila_SoC/D_Cache/miss_read[20]} {Aquila_SoC/D_Cache/miss_read[21]} {Aquila_SoC/D_Cache/miss_read[22]} {Aquila_SoC/D_Cache/miss_read[23]} {Aquila_SoC/D_Cache/miss_read[24]} {Aquila_SoC/D_Cache/miss_read[25]} {Aquila_SoC/D_Cache/miss_read[26]} {Aquila_SoC/D_Cache/miss_read[27]} {Aquila_SoC/D_Cache/miss_read[28]} {Aquila_SoC/D_Cache/miss_read[29]} {Aquila_SoC/D_Cache/miss_read[30]} {Aquila_SoC/D_Cache/miss_read[31]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {Aquila_SoC/D_Cache/miss_write[0]} {Aquila_SoC/D_Cache/miss_write[1]} {Aquila_SoC/D_Cache/miss_write[2]} {Aquila_SoC/D_Cache/miss_write[3]} {Aquila_SoC/D_Cache/miss_write[4]} {Aquila_SoC/D_Cache/miss_write[5]} {Aquila_SoC/D_Cache/miss_write[6]} {Aquila_SoC/D_Cache/miss_write[7]} {Aquila_SoC/D_Cache/miss_write[8]} {Aquila_SoC/D_Cache/miss_write[9]} {Aquila_SoC/D_Cache/miss_write[10]} {Aquila_SoC/D_Cache/miss_write[11]} {Aquila_SoC/D_Cache/miss_write[12]} {Aquila_SoC/D_Cache/miss_write[13]} {Aquila_SoC/D_Cache/miss_write[14]} {Aquila_SoC/D_Cache/miss_write[15]} {Aquila_SoC/D_Cache/miss_write[16]} {Aquila_SoC/D_Cache/miss_write[17]} {Aquila_SoC/D_Cache/miss_write[18]} {Aquila_SoC/D_Cache/miss_write[19]} {Aquila_SoC/D_Cache/miss_write[20]} {Aquila_SoC/D_Cache/miss_write[21]} {Aquila_SoC/D_Cache/miss_write[22]} {Aquila_SoC/D_Cache/miss_write[23]} {Aquila_SoC/D_Cache/miss_write[24]} {Aquila_SoC/D_Cache/miss_write[25]} {Aquila_SoC/D_Cache/miss_write[26]} {Aquila_SoC/D_Cache/miss_write[27]} {Aquila_SoC/D_Cache/miss_write[28]} {Aquila_SoC/D_Cache/miss_write[29]} {Aquila_SoC/D_Cache/miss_write[30]} {Aquila_SoC/D_Cache/miss_write[31]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {Aquila_SoC/D_Cache/total[0]} {Aquila_SoC/D_Cache/total[1]} {Aquila_SoC/D_Cache/total[2]} {Aquila_SoC/D_Cache/total[3]} {Aquila_SoC/D_Cache/total[4]} {Aquila_SoC/D_Cache/total[5]} {Aquila_SoC/D_Cache/total[6]} {Aquila_SoC/D_Cache/total[7]} {Aquila_SoC/D_Cache/total[8]} {Aquila_SoC/D_Cache/total[9]} {Aquila_SoC/D_Cache/total[10]} {Aquila_SoC/D_Cache/total[11]} {Aquila_SoC/D_Cache/total[12]} {Aquila_SoC/D_Cache/total[13]} {Aquila_SoC/D_Cache/total[14]} {Aquila_SoC/D_Cache/total[15]} {Aquila_SoC/D_Cache/total[16]} {Aquila_SoC/D_Cache/total[17]} {Aquila_SoC/D_Cache/total[18]} {Aquila_SoC/D_Cache/total[19]} {Aquila_SoC/D_Cache/total[20]} {Aquila_SoC/D_Cache/total[21]} {Aquila_SoC/D_Cache/total[22]} {Aquila_SoC/D_Cache/total[23]} {Aquila_SoC/D_Cache/total[24]} {Aquila_SoC/D_Cache/total[25]} {Aquila_SoC/D_Cache/total[26]} {Aquila_SoC/D_Cache/total[27]} {Aquila_SoC/D_Cache/total[28]} {Aquila_SoC/D_Cache/total[29]} {Aquila_SoC/D_Cache/total[30]} {Aquila_SoC/D_Cache/total[31]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {Aquila_SoC/D_Cache/read[0]} {Aquila_SoC/D_Cache/read[1]} {Aquila_SoC/D_Cache/read[2]} {Aquila_SoC/D_Cache/read[3]} {Aquila_SoC/D_Cache/read[4]} {Aquila_SoC/D_Cache/read[5]} {Aquila_SoC/D_Cache/read[6]} {Aquila_SoC/D_Cache/read[7]} {Aquila_SoC/D_Cache/read[8]} {Aquila_SoC/D_Cache/read[9]} {Aquila_SoC/D_Cache/read[10]} {Aquila_SoC/D_Cache/read[11]} {Aquila_SoC/D_Cache/read[12]} {Aquila_SoC/D_Cache/read[13]} {Aquila_SoC/D_Cache/read[14]} {Aquila_SoC/D_Cache/read[15]} {Aquila_SoC/D_Cache/read[16]} {Aquila_SoC/D_Cache/read[17]} {Aquila_SoC/D_Cache/read[18]} {Aquila_SoC/D_Cache/read[19]} {Aquila_SoC/D_Cache/read[20]} {Aquila_SoC/D_Cache/read[21]} {Aquila_SoC/D_Cache/read[22]} {Aquila_SoC/D_Cache/read[23]} {Aquila_SoC/D_Cache/read[24]} {Aquila_SoC/D_Cache/read[25]} {Aquila_SoC/D_Cache/read[26]} {Aquila_SoC/D_Cache/read[27]} {Aquila_SoC/D_Cache/read[28]} {Aquila_SoC/D_Cache/read[29]} {Aquila_SoC/D_Cache/read[30]} {Aquila_SoC/D_Cache/read[31]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {Aquila_SoC/D_Cache/write[0]} {Aquila_SoC/D_Cache/write[1]} {Aquila_SoC/D_Cache/write[2]} {Aquila_SoC/D_Cache/write[3]} {Aquila_SoC/D_Cache/write[4]} {Aquila_SoC/D_Cache/write[5]} {Aquila_SoC/D_Cache/write[6]} {Aquila_SoC/D_Cache/write[7]} {Aquila_SoC/D_Cache/write[8]} {Aquila_SoC/D_Cache/write[9]} {Aquila_SoC/D_Cache/write[10]} {Aquila_SoC/D_Cache/write[11]} {Aquila_SoC/D_Cache/write[12]} {Aquila_SoC/D_Cache/write[13]} {Aquila_SoC/D_Cache/write[14]} {Aquila_SoC/D_Cache/write[15]} {Aquila_SoC/D_Cache/write[16]} {Aquila_SoC/D_Cache/write[17]} {Aquila_SoC/D_Cache/write[18]} {Aquila_SoC/D_Cache/write[19]} {Aquila_SoC/D_Cache/write[20]} {Aquila_SoC/D_Cache/write[21]} {Aquila_SoC/D_Cache/write[22]} {Aquila_SoC/D_Cache/write[23]} {Aquila_SoC/D_Cache/write[24]} {Aquila_SoC/D_Cache/write[25]} {Aquila_SoC/D_Cache/write[26]} {Aquila_SoC/D_Cache/write[27]} {Aquila_SoC/D_Cache/write[28]} {Aquila_SoC/D_Cache/write[29]} {Aquila_SoC/D_Cache/write[30]} {Aquila_SoC/D_Cache/write[31]}]]

connect_debug_port u_ila_0/probe1 [get_nets [list {Aquila_SoC/D_Cache/hit_latency[0]} {Aquila_SoC/D_Cache/hit_latency[1]} {Aquila_SoC/D_Cache/hit_latency[2]} {Aquila_SoC/D_Cache/hit_latency[3]} {Aquila_SoC/D_Cache/hit_latency[4]} {Aquila_SoC/D_Cache/hit_latency[5]} {Aquila_SoC/D_Cache/hit_latency[6]} {Aquila_SoC/D_Cache/hit_latency[7]} {Aquila_SoC/D_Cache/hit_latency[8]} {Aquila_SoC/D_Cache/hit_latency[9]} {Aquila_SoC/D_Cache/hit_latency[10]} {Aquila_SoC/D_Cache/hit_latency[11]} {Aquila_SoC/D_Cache/hit_latency[12]} {Aquila_SoC/D_Cache/hit_latency[13]} {Aquila_SoC/D_Cache/hit_latency[14]} {Aquila_SoC/D_Cache/hit_latency[15]} {Aquila_SoC/D_Cache/hit_latency[16]} {Aquila_SoC/D_Cache/hit_latency[17]} {Aquila_SoC/D_Cache/hit_latency[18]} {Aquila_SoC/D_Cache/hit_latency[19]} {Aquila_SoC/D_Cache/hit_latency[20]} {Aquila_SoC/D_Cache/hit_latency[21]} {Aquila_SoC/D_Cache/hit_latency[22]} {Aquila_SoC/D_Cache/hit_latency[23]} {Aquila_SoC/D_Cache/hit_latency[24]} {Aquila_SoC/D_Cache/hit_latency[25]} {Aquila_SoC/D_Cache/hit_latency[26]} {Aquila_SoC/D_Cache/hit_latency[27]} {Aquila_SoC/D_Cache/hit_latency[28]} {Aquila_SoC/D_Cache/hit_latency[29]} {Aquila_SoC/D_Cache/hit_latency[30]} {Aquila_SoC/D_Cache/hit_latency[31]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {Aquila_SoC/D_Cache/read_latency[0]} {Aquila_SoC/D_Cache/read_latency[1]} {Aquila_SoC/D_Cache/read_latency[2]} {Aquila_SoC/D_Cache/read_latency[3]} {Aquila_SoC/D_Cache/read_latency[4]} {Aquila_SoC/D_Cache/read_latency[5]} {Aquila_SoC/D_Cache/read_latency[6]} {Aquila_SoC/D_Cache/read_latency[7]} {Aquila_SoC/D_Cache/read_latency[8]} {Aquila_SoC/D_Cache/read_latency[9]} {Aquila_SoC/D_Cache/read_latency[10]} {Aquila_SoC/D_Cache/read_latency[11]} {Aquila_SoC/D_Cache/read_latency[12]} {Aquila_SoC/D_Cache/read_latency[13]} {Aquila_SoC/D_Cache/read_latency[14]} {Aquila_SoC/D_Cache/read_latency[15]} {Aquila_SoC/D_Cache/read_latency[16]} {Aquila_SoC/D_Cache/read_latency[17]} {Aquila_SoC/D_Cache/read_latency[18]} {Aquila_SoC/D_Cache/read_latency[19]} {Aquila_SoC/D_Cache/read_latency[20]} {Aquila_SoC/D_Cache/read_latency[21]} {Aquila_SoC/D_Cache/read_latency[22]} {Aquila_SoC/D_Cache/read_latency[23]} {Aquila_SoC/D_Cache/read_latency[24]} {Aquila_SoC/D_Cache/read_latency[25]} {Aquila_SoC/D_Cache/read_latency[26]} {Aquila_SoC/D_Cache/read_latency[27]} {Aquila_SoC/D_Cache/read_latency[28]} {Aquila_SoC/D_Cache/read_latency[29]} {Aquila_SoC/D_Cache/read_latency[30]} {Aquila_SoC/D_Cache/read_latency[31]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {Aquila_SoC/D_Cache/miss_latency[0]} {Aquila_SoC/D_Cache/miss_latency[1]} {Aquila_SoC/D_Cache/miss_latency[2]} {Aquila_SoC/D_Cache/miss_latency[3]} {Aquila_SoC/D_Cache/miss_latency[4]} {Aquila_SoC/D_Cache/miss_latency[5]} {Aquila_SoC/D_Cache/miss_latency[6]} {Aquila_SoC/D_Cache/miss_latency[7]} {Aquila_SoC/D_Cache/miss_latency[8]} {Aquila_SoC/D_Cache/miss_latency[9]} {Aquila_SoC/D_Cache/miss_latency[10]} {Aquila_SoC/D_Cache/miss_latency[11]} {Aquila_SoC/D_Cache/miss_latency[12]} {Aquila_SoC/D_Cache/miss_latency[13]} {Aquila_SoC/D_Cache/miss_latency[14]} {Aquila_SoC/D_Cache/miss_latency[15]} {Aquila_SoC/D_Cache/miss_latency[16]} {Aquila_SoC/D_Cache/miss_latency[17]} {Aquila_SoC/D_Cache/miss_latency[18]} {Aquila_SoC/D_Cache/miss_latency[19]} {Aquila_SoC/D_Cache/miss_latency[20]} {Aquila_SoC/D_Cache/miss_latency[21]} {Aquila_SoC/D_Cache/miss_latency[22]} {Aquila_SoC/D_Cache/miss_latency[23]} {Aquila_SoC/D_Cache/miss_latency[24]} {Aquila_SoC/D_Cache/miss_latency[25]} {Aquila_SoC/D_Cache/miss_latency[26]} {Aquila_SoC/D_Cache/miss_latency[27]} {Aquila_SoC/D_Cache/miss_latency[28]} {Aquila_SoC/D_Cache/miss_latency[29]} {Aquila_SoC/D_Cache/miss_latency[30]} {Aquila_SoC/D_Cache/miss_latency[31]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {Aquila_SoC/D_Cache/write_latency[0]} {Aquila_SoC/D_Cache/write_latency[1]} {Aquila_SoC/D_Cache/write_latency[2]} {Aquila_SoC/D_Cache/write_latency[3]} {Aquila_SoC/D_Cache/write_latency[4]} {Aquila_SoC/D_Cache/write_latency[5]} {Aquila_SoC/D_Cache/write_latency[6]} {Aquila_SoC/D_Cache/write_latency[7]} {Aquila_SoC/D_Cache/write_latency[8]} {Aquila_SoC/D_Cache/write_latency[9]} {Aquila_SoC/D_Cache/write_latency[10]} {Aquila_SoC/D_Cache/write_latency[11]} {Aquila_SoC/D_Cache/write_latency[12]} {Aquila_SoC/D_Cache/write_latency[13]} {Aquila_SoC/D_Cache/write_latency[14]} {Aquila_SoC/D_Cache/write_latency[15]} {Aquila_SoC/D_Cache/write_latency[16]} {Aquila_SoC/D_Cache/write_latency[17]} {Aquila_SoC/D_Cache/write_latency[18]} {Aquila_SoC/D_Cache/write_latency[19]} {Aquila_SoC/D_Cache/write_latency[20]} {Aquila_SoC/D_Cache/write_latency[21]} {Aquila_SoC/D_Cache/write_latency[22]} {Aquila_SoC/D_Cache/write_latency[23]} {Aquila_SoC/D_Cache/write_latency[24]} {Aquila_SoC/D_Cache/write_latency[25]} {Aquila_SoC/D_Cache/write_latency[26]} {Aquila_SoC/D_Cache/write_latency[27]} {Aquila_SoC/D_Cache/write_latency[28]} {Aquila_SoC/D_Cache/write_latency[29]} {Aquila_SoC/D_Cache/write_latency[30]} {Aquila_SoC/D_Cache/write_latency[31]}]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {Aquila_SoC/D_Cache/S[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[0]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[1]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[2]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[3]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[4]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[5]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[6]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[7]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[8]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[9]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[10]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[11]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[12]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[13]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[14]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[15]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[16]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[17]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[18]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[19]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[20]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[21]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[22]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[23]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[24]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[25]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[26]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[27]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[28]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[29]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[30]} {Aquila_SoC/RISCV_CORE0/Fetch/pc_o_reg[31]_0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list Aquila_SoC/D_Cache/cache_hit]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list Aquila_SoC/p_rw_i0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list Aquila_SoC/p_strobe_i0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list Aquila_SoC/D_Cache/rw]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_BUFG]
