# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/a609071103.cs07/Documents/micro processor/HW5/aquila_dram/aquila_dram.srcs/sources_1/ip/async_fifo_addr/async_fifo_addr.xci
# IP: The module: 'async_fifo_addr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/a609071103.cs07/Documents/micro processor/HW5/aquila_dram/aquila_dram.gen/sources_1/ip/async_fifo_addr/async_fifo_addr.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_addr'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/a609071103.cs07/Documents/micro processor/HW5/aquila_dram/aquila_dram.gen/sources_1/ip/async_fifo_addr/async_fifo_addr_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_addr'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/a609071103.cs07/Documents/micro processor/HW5/aquila_dram/aquila_dram.gen/sources_1/ip/async_fifo_addr/async_fifo_addr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_addr'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/a609071103.cs07/Documents/micro processor/HW5/aquila_dram/aquila_dram.srcs/sources_1/ip/async_fifo_addr/async_fifo_addr.xci
# IP: The module: 'async_fifo_addr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/a609071103.cs07/Documents/micro processor/HW5/aquila_dram/aquila_dram.gen/sources_1/ip/async_fifo_addr/async_fifo_addr.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_addr'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/a609071103.cs07/Documents/micro processor/HW5/aquila_dram/aquila_dram.gen/sources_1/ip/async_fifo_addr/async_fifo_addr_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_addr'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/a609071103.cs07/Documents/micro processor/HW5/aquila_dram/aquila_dram.gen/sources_1/ip/async_fifo_addr/async_fifo_addr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_addr'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
