set_property SRC_FILE_INFO {cfile:{C:/Users/a609071103.cs07/Documents/micro processor/HW4/aquila_sd/aquila_sd/aquila_sd/aquila_sd.srcs/constrs_1/imports/xdc/arty.xdc} rfile:../../../aquila_sd.srcs/constrs_1/imports/xdc/arty.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports sysclk_i]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports resetn_i]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports {usr_led[0]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {usr_led[1]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {usr_led[2]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {usr_led[3]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D9 IOSTANDARD LVCMOS33} [get_ports {usr_btn[0]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C9 IOSTANDARD LVCMOS33} [get_ports {usr_btn[1]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B9 IOSTANDARD LVCMOS33} [get_ports {usr_btn[2]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B8 IOSTANDARD LVCMOS33} [get_ports {usr_btn[3]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports uart_tx]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A9 IOSTANDARD LVCMOS33} [get_ports uart_rx]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports spi_miso]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports spi_mosi]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS33} [get_ports spi_sck]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C1 IOSTANDARD LVCMOS33} [get_ports spi_ss]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clk_BUFG]]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {Aquila_SoC/RISCV_CORE0/context_overhead[0]} {Aquila_SoC/RISCV_CORE0/context_overhead[1]} {Aquila_SoC/RISCV_CORE0/context_overhead[2]} {Aquila_SoC/RISCV_CORE0/context_overhead[3]} {Aquila_SoC/RISCV_CORE0/context_overhead[4]} {Aquila_SoC/RISCV_CORE0/context_overhead[5]} {Aquila_SoC/RISCV_CORE0/context_overhead[6]} {Aquila_SoC/RISCV_CORE0/context_overhead[7]} {Aquila_SoC/RISCV_CORE0/context_overhead[8]} {Aquila_SoC/RISCV_CORE0/context_overhead[9]} {Aquila_SoC/RISCV_CORE0/context_overhead[10]} {Aquila_SoC/RISCV_CORE0/context_overhead[11]} {Aquila_SoC/RISCV_CORE0/context_overhead[12]} {Aquila_SoC/RISCV_CORE0/context_overhead[13]} {Aquila_SoC/RISCV_CORE0/context_overhead[14]} {Aquila_SoC/RISCV_CORE0/context_overhead[15]} {Aquila_SoC/RISCV_CORE0/context_overhead[16]} {Aquila_SoC/RISCV_CORE0/context_overhead[17]} {Aquila_SoC/RISCV_CORE0/context_overhead[18]} {Aquila_SoC/RISCV_CORE0/context_overhead[19]} {Aquila_SoC/RISCV_CORE0/context_overhead[20]} {Aquila_SoC/RISCV_CORE0/context_overhead[21]} {Aquila_SoC/RISCV_CORE0/context_overhead[22]} {Aquila_SoC/RISCV_CORE0/context_overhead[23]} {Aquila_SoC/RISCV_CORE0/context_overhead[24]} {Aquila_SoC/RISCV_CORE0/context_overhead[25]} {Aquila_SoC/RISCV_CORE0/context_overhead[26]} {Aquila_SoC/RISCV_CORE0/context_overhead[27]} {Aquila_SoC/RISCV_CORE0/context_overhead[28]} {Aquila_SoC/RISCV_CORE0/context_overhead[29]} {Aquila_SoC/RISCV_CORE0/context_overhead[30]} {Aquila_SoC/RISCV_CORE0/context_overhead[31]}]]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {Aquila_SoC/RISCV_CORE0/critical_overhead[0]} {Aquila_SoC/RISCV_CORE0/critical_overhead[1]} {Aquila_SoC/RISCV_CORE0/critical_overhead[2]} {Aquila_SoC/RISCV_CORE0/critical_overhead[3]} {Aquila_SoC/RISCV_CORE0/critical_overhead[4]} {Aquila_SoC/RISCV_CORE0/critical_overhead[5]} {Aquila_SoC/RISCV_CORE0/critical_overhead[6]} {Aquila_SoC/RISCV_CORE0/critical_overhead[7]} {Aquila_SoC/RISCV_CORE0/critical_overhead[8]} {Aquila_SoC/RISCV_CORE0/critical_overhead[9]} {Aquila_SoC/RISCV_CORE0/critical_overhead[10]} {Aquila_SoC/RISCV_CORE0/critical_overhead[11]} {Aquila_SoC/RISCV_CORE0/critical_overhead[12]} {Aquila_SoC/RISCV_CORE0/critical_overhead[13]} {Aquila_SoC/RISCV_CORE0/critical_overhead[14]} {Aquila_SoC/RISCV_CORE0/critical_overhead[15]} {Aquila_SoC/RISCV_CORE0/critical_overhead[16]} {Aquila_SoC/RISCV_CORE0/critical_overhead[17]} {Aquila_SoC/RISCV_CORE0/critical_overhead[18]} {Aquila_SoC/RISCV_CORE0/critical_overhead[19]} {Aquila_SoC/RISCV_CORE0/critical_overhead[20]} {Aquila_SoC/RISCV_CORE0/critical_overhead[21]} {Aquila_SoC/RISCV_CORE0/critical_overhead[22]} {Aquila_SoC/RISCV_CORE0/critical_overhead[23]} {Aquila_SoC/RISCV_CORE0/critical_overhead[24]} {Aquila_SoC/RISCV_CORE0/critical_overhead[25]} {Aquila_SoC/RISCV_CORE0/critical_overhead[26]} {Aquila_SoC/RISCV_CORE0/critical_overhead[27]} {Aquila_SoC/RISCV_CORE0/critical_overhead[28]} {Aquila_SoC/RISCV_CORE0/critical_overhead[29]} {Aquila_SoC/RISCV_CORE0/critical_overhead[30]} {Aquila_SoC/RISCV_CORE0/critical_overhead[31]}]]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {Aquila_SoC/RISCV_CORE0/critical_overhead2[0]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[1]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[2]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[3]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[4]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[5]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[6]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[7]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[8]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[9]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[10]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[11]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[12]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[13]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[14]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[15]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[16]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[17]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[18]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[19]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[20]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[21]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[22]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[23]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[24]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[25]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[26]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[27]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[28]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[29]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[30]} {Aquila_SoC/RISCV_CORE0/critical_overhead2[31]}]]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {Aquila_SoC/RISCV_CORE0/dec_pc[0]} {Aquila_SoC/RISCV_CORE0/dec_pc[1]} {Aquila_SoC/RISCV_CORE0/dec_pc[2]} {Aquila_SoC/RISCV_CORE0/dec_pc[3]} {Aquila_SoC/RISCV_CORE0/dec_pc[4]} {Aquila_SoC/RISCV_CORE0/dec_pc[5]} {Aquila_SoC/RISCV_CORE0/dec_pc[6]} {Aquila_SoC/RISCV_CORE0/dec_pc[7]} {Aquila_SoC/RISCV_CORE0/dec_pc[8]} {Aquila_SoC/RISCV_CORE0/dec_pc[9]} {Aquila_SoC/RISCV_CORE0/dec_pc[10]} {Aquila_SoC/RISCV_CORE0/dec_pc[11]} {Aquila_SoC/RISCV_CORE0/dec_pc[12]} {Aquila_SoC/RISCV_CORE0/dec_pc[13]} {Aquila_SoC/RISCV_CORE0/dec_pc[14]} {Aquila_SoC/RISCV_CORE0/dec_pc[15]} {Aquila_SoC/RISCV_CORE0/dec_pc[16]} {Aquila_SoC/RISCV_CORE0/dec_pc[17]} {Aquila_SoC/RISCV_CORE0/dec_pc[18]} {Aquila_SoC/RISCV_CORE0/dec_pc[19]} {Aquila_SoC/RISCV_CORE0/dec_pc[20]} {Aquila_SoC/RISCV_CORE0/dec_pc[21]} {Aquila_SoC/RISCV_CORE0/dec_pc[22]} {Aquila_SoC/RISCV_CORE0/dec_pc[23]} {Aquila_SoC/RISCV_CORE0/dec_pc[24]} {Aquila_SoC/RISCV_CORE0/dec_pc[25]} {Aquila_SoC/RISCV_CORE0/dec_pc[26]} {Aquila_SoC/RISCV_CORE0/dec_pc[27]} {Aquila_SoC/RISCV_CORE0/dec_pc[28]} {Aquila_SoC/RISCV_CORE0/dec_pc[29]} {Aquila_SoC/RISCV_CORE0/dec_pc[30]} {Aquila_SoC/RISCV_CORE0/dec_pc[31]}]]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {Aquila_SoC/RISCV_CORE0/pcu_pc[0]} {Aquila_SoC/RISCV_CORE0/pcu_pc[1]} {Aquila_SoC/RISCV_CORE0/pcu_pc[2]} {Aquila_SoC/RISCV_CORE0/pcu_pc[3]} {Aquila_SoC/RISCV_CORE0/pcu_pc[4]} {Aquila_SoC/RISCV_CORE0/pcu_pc[5]} {Aquila_SoC/RISCV_CORE0/pcu_pc[6]} {Aquila_SoC/RISCV_CORE0/pcu_pc[7]} {Aquila_SoC/RISCV_CORE0/pcu_pc[8]} {Aquila_SoC/RISCV_CORE0/pcu_pc[9]} {Aquila_SoC/RISCV_CORE0/pcu_pc[10]} {Aquila_SoC/RISCV_CORE0/pcu_pc[11]} {Aquila_SoC/RISCV_CORE0/pcu_pc[12]} {Aquila_SoC/RISCV_CORE0/pcu_pc[13]} {Aquila_SoC/RISCV_CORE0/pcu_pc[14]} {Aquila_SoC/RISCV_CORE0/pcu_pc[15]} {Aquila_SoC/RISCV_CORE0/pcu_pc[16]} {Aquila_SoC/RISCV_CORE0/pcu_pc[17]} {Aquila_SoC/RISCV_CORE0/pcu_pc[18]} {Aquila_SoC/RISCV_CORE0/pcu_pc[19]} {Aquila_SoC/RISCV_CORE0/pcu_pc[20]} {Aquila_SoC/RISCV_CORE0/pcu_pc[21]} {Aquila_SoC/RISCV_CORE0/pcu_pc[22]} {Aquila_SoC/RISCV_CORE0/pcu_pc[23]} {Aquila_SoC/RISCV_CORE0/pcu_pc[24]} {Aquila_SoC/RISCV_CORE0/pcu_pc[25]} {Aquila_SoC/RISCV_CORE0/pcu_pc[26]} {Aquila_SoC/RISCV_CORE0/pcu_pc[27]} {Aquila_SoC/RISCV_CORE0/pcu_pc[28]} {Aquila_SoC/RISCV_CORE0/pcu_pc[29]} {Aquila_SoC/RISCV_CORE0/pcu_pc[30]} {Aquila_SoC/RISCV_CORE0/pcu_pc[31]}]]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {Aquila_SoC/RISCV_CORE0/semaphre_overhead[0]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[1]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[2]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[3]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[4]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[5]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[6]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[7]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[8]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[9]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[10]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[11]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[12]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[13]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[14]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[15]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[16]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[17]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[18]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[19]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[20]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[21]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[22]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[23]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[24]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[25]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[26]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[27]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[28]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[29]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[30]} {Aquila_SoC/RISCV_CORE0/semaphre_overhead[31]}]]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list Aquila_SoC/RISCV_CORE0/irq_taken]]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk_BUFG]
